### ISSUE TITLE
/mappy help not showing the list of commands

### ISSUE THREAD

**Issue by Spanglish1337** [MidoriKami/Mappy#1]
Title,

not showing in-game for some reason.

Is there a way to list the commands on the README file on the main page here?

**Comment by MidoriKami** [comment]
Commands are not implemented yet.
They are on my Todo List, albeit not high priority.

Use `/mappy` and configure via the configuration window.

**Comment by Spanglish1337** [comment]
Whoops!,

Thank you for the clarification!
