### ISSUE TITLE
[Bug] Multi-monitor prevents proper redraw of map

### ISSUE THREAD

**Issue by NadyaNayme** [MidoriKami/Mappy#100]
Open Mappy on 2nd monitor and zoom in/out the map and it doesn't redraw properly. Moving it back to the primary monitor, zooming, and moving it back to the secondary monitor fixes things as a workaround.

I'm sure this has something to do with the semi-experimental nature of multi-monitor mode to begin with so not sure if there's even anything you can do to fix this. Reporting it in the offhand-chance there is.

![image](https://github.com/MidoriKami/Mappy/assets/4567166/8832328c-d378-4460-bcd0-7af3f5a211ad)

Luckily I don't zoom my map since the entire point of Mappy on a 2nd monitor is to have it large enough to where I never need to mess with the zoom setting in the first place. I only discovered this because I positioned Mappy before resizing.

**Comment by MidoriKami** [comment]
Transparency is not supported in multimontior mode, this is a dalamud/imgui thing and nothing I have any control over.
