### ISSUE TITLE
[Bug] Window Focus/Fade Issues

### ISSUE THREAD

**Issue by HawkAtreides** [MidoriKami/Mappy#102]
Some issues I'm having with the window focus and fade features:

1. The "Always" option on the "Window Fade" tab doesn't seem to actually do anything. If I have "Always" set but no other option, the window displays at full opacity at all times, even if the opacity is set lower than 1.
2. The "When Moving" option causes some flickering between opacity settings at the slightest pause in movement, and could likely use a hysteresis feature (perhaps a user-configurable delay between the end of movement and falling back to another state).
3. The "Hide During Combat" feature correctly hides the map when combat begins, but when the map is displayed again after combat it's in the focused state. This exacerbates the flickering issue with the "When Moving" setting, as I have the map at full opacity when focused but partially transparent otherwise.

**Comment by MidoriKami** [comment]
duplicate #92

Going to close this and keep 92 open, this'll link them together for tracking purposes.
