### ISSUE TITLE
[Bug] Gemstone Trader quest icon is sometimes a massive scale

### ISSUE THREAD

**Issue by zbee** [MidoriKami/Mappy#105]
I have encountered this issue several times now, and it's always only with this Gemstone Trader unlock quest icon, it will just be very very large in the config window and on the map.

I have not found a consistent way to replicate this issue, it has occurred on some restarts and not others, without settings for Mappy persisting between restarts.
My only idea is that I've always noticed it while I am in such a zone with this marker for the first time per launch after being in many other zones, but it hasn't occurred every time that's the case.

![image](https://github.com/user-attachments/assets/5afb7170-37a7-43d3-bd1a-b9e0c2b62592)

**Comment by MidoriKami** [comment]
duplicate #85
