### ISSUE TITLE
When using 'gather' option with Gatherbuddy, map sometimes switches to incorrect area or doesn't switch at all

### ISSUE THREAD

**Issue by nicuity** [MidoriKami/Mappy#107]
This does not currently happen with in-game map. I've also found it sometimes does not center to the node.

One way I reproduced the bug is TPing to my FC house then using the 'gather' option with gatherbuddy through the gathering log. Not 100% unfortunately.
![mappy](https://github.com/user-attachments/assets/7cf24ed7-d1a2-42b9-9c93-3654d7e274fb)

**Comment by MidoriKami** [comment]
Duplicate #98 
I don't care if you disagree that is a duplicate this is how I'm tracking issues and fixed. The fix for that will fix this.
