### ISSUE TITLE
[Suggestion] Party members, other alliances, and random players used to be separate

### ISSUE THREAD

**Issue by zbee** [MidoriKami/Mappy#108]
Party members, other alliance members, and random players all used to be separate icons that could be controlled separately from each other.
Suggestion is that this behavior be re-implemented.

**Comment by MidoriKami** [comment]
Not planned. Configuration is per icon.

**Comment by zbee** [comment]
> Configuration is per icon.

Just to clarify: They _were_ separate, unique icons before.

**Comment by MidoriKami** [comment]
Yes, and I changed that, on purpose.

**Comment by zbee** [comment]
revived at #122
