### ISSUE TITLE
Scaling icons based on zoom

### ISSUE THREAD

**Issue by foophoof** [MidoriKami/Mappy#110]
Since the icons scale depending on zoom (or don't scale, depending on how you look at it, I guess), if you are somewhat zoomed out on the map I find it very difficult to see the various icons.

It would be nice to have the feature like the native map where the icons stay the same (pixel/screen-space) size regardless of zoom level. I think this is how old Mappy worked too?

**Comment by foophoof** [comment]
...I'm not sure how I missed the "Scale icons with zoom" checkbox, nevermind, this is already in the plugin.

**Comment by MidoriKami** [comment]
The config UI could be better.

**Comment by MidoriKami** [comment]
The config ui is now better.
