### ISSUE TITLE
[Bug]? Mappy quest list window showing all quests in Accepted tab

### ISSUE THREAD

**Issue by boogieman1402** [MidoriKami/Mappy#114]
**Expected behaviour**
From the question mark explanation, I gather that the window is supposed to show only quests for the current zone. This appears to work for the Unaccepted tab.

**Observed behaviour**
The Accepted tab shows all my open quests, see screenshot
https://i.imgur.com/ix3yiJx.png

Setting the show/hide marks in the Journal makes no difference.

**Comment by MidoriKami** [comment]
Working as intended.
