### ISSUE TITLE
Dalamud Multi-monitors setting + Mappy Hide Window Frame rendering issue

### ISSUE THREAD

**Issue by TheLostSoul** [MidoriKami/Mappy#116]
I'm not sure if this is a you issue or something with Dalamud, but I don't know any other plugins that draw movable images. I'm also not sure if this type of usage is considered as "using Mappy to replace the minimap" disclaimer you've had in the past.

Actual:
When the border is hidden and drawn outside of the game window, the Mappy window does not clear its render buffer when moving the map (the map looks like the winning screen of Solitaire).

Expected:
The map rendering should behave as it does with the frame shown.

Steps to Reproduce:
1. Enable Multi-monitor setting in Dalamud.
2. Move Mappy window to a monitor the game is not rendering on.
3. Enable the "Hide Window Frame" option in Mappy.
4. Move/scroll the map around the window.

![image](https://github.com/user-attachments/assets/f1b85062-a84c-45cc-86ce-004132e84a06)

**Comment by MidoriKami** [comment]
Duplicate #100
