### ISSUE TITLE
[Bug] Using Map modification mods does not apply to Mappy

### ISSUE THREAD

**Issue by goldeye75** [MidoriKami/Mappy#118]
Hi,

In previous version before 7.0, the Mappy version was able to be compatible with Map modification mods that manipulate the files. Which is https://github.com/RKI027/ffxiv-huntmaps/releases/tag/v7.0.0. Just manipulates the location data.

In 3.0, this functionality is not working.

If you can fix it great. If not, can justify the reasoning for it. Just wanted to understand from the backend perspective

**Comment by MidoriKami** [comment]
Duplicate #97
