### ISSUE TITLE
[Request] Lock map zoom state, or setting/button to set current map zoom to width of window

### ISSUE THREAD

**Issue by masanbol** [MidoriKami/Mappy#119]
Would be nice to have the ability to lock/save the current zoom level of the map and have it persist between sessions/other maps, and/or an option to have it fill the current Mappy window edge-to-edge. I typically play on a large screen with the map open and I like to see it in full width without moving it around at all.

Thanks!

**Comment by MidoriKami** [comment]
I'm in favor of a zoom lock, but the question is how would a user set it, I don't want to clutter the tool bar if I can help it

**Comment by masanbol** [comment]
I agree with that - maybe in the settings?

**Comment by MidoriKami** [comment]
Then they wouldn't be able to disable it in an easy way, most people wouldn't want locked zoom all the time, probably only sometimes

**Comment by masanbol** [comment]
Right now the toolbar has six icons, seven counting the settings toggle in the top right. Based on the size of the other icons and the amount of space they take up I think adding it wouldn't clutter it up too bad, but I'll defer to you on what method you prefer.

**Comment by MidoriKami** [comment]
What about a config option that adds an entry to the context menu?

**Comment by masanbol** [comment]
Context menu is the right click menu? That would work!
