### ISSUE TITLE
[Bug] Coordinates bar is 1px from the bottom

### ISSUE THREAD

**Issue by zbee** [MidoriKami/Mappy#124]
The coordinates bar is 1px from the bottom of the map window.

![image](https://github.com/user-attachments/assets/fbcddcd8-ad5a-4156-9892-d026afb6f7bd)

Tried on various window sizes and positions.

Switching between Dalamud styles does not fix it.

**Comment by MidoriKami** [comment]
![image](https://github.com/user-attachments/assets/62b98d92-6690-42da-8ecd-b122f7600dd8)
I'm not seeing this myself

**Comment by zbee** [comment]
It's a font scale thing again: anything other than 100% seems to cause this gap.

**Comment by MidoriKami** [comment]
Odd because I account for scale with every part of the calculation

```cs
        var coordinateBarSize = new Vector2(ImGui.GetContentRegionMax().X, 20.0f * ImGuiHelpers.GlobalScale);
        ImGui.SetCursorPos(ImGui.GetContentRegionMax() - coordinateBarSize);
        
        using var childBackgroundStyle = ImRaii.PushColor(ImGuiCol.ChildBg, Vector4.Zero with { W = System.SystemConfig.CoordinateBarFade });
        using var coordinateChild = ImRaii.Child("coordinate_child", coordinateBarSize);
        if (!coordinateChild) return;
```

**Comment by MidoriKami** [comment]
![image](https://github.com/user-attachments/assets/3d37b1ad-cbab-4e4f-b58f-bc384e7ee29a)

I still don't see it at 200% dalamud global font scale

**Comment by zbee** [comment]
Check the 117% button, or I'm on 91% personally.
But yeah, don't see it on any of the other preset scale options, but do on every value between them it seems.

Probably the same thing [we discussed](https://discord.com/channels/581875019861328007/1143586307914862592/1260659946207580383) about SortaKinda.

**Comment by zbee** [comment]
Were you not able to reproduce on the 117% preset, or any custom value? If so I'll keep investigating the issue.
Or is only 100% font scale support planned? If so I'll work on a PR.
