### ISSUE TITLE
[Suggestion] Separate coordinates

### ISSUE THREAD

**Issue by zbee** [MidoriKami/Mappy#125]
There is no comma, or X/Y label like on the vanilla map, between either set of coordinates making them more difficult to read than they need to be.

![image](https://github.com/user-attachments/assets/e369c4e8-aa7d-4a55-9e1d-d1fe38339bfe)
![image](https://github.com/user-attachments/assets/2df1c06b-3990-4099-a2ac-53297e1aa94c)

Dalamud style does not affect the gap size.

**Comment by MidoriKami** [comment]
I didn't really like how it looked with a comma, is it really worth it?

**Comment by zbee** [comment]
I don't either, and the X and Y labels seem like too much, but I do think there needs to be something.
Maybe just more gap would be best?

**Comment by GayPotatoEmma** [comment]
Maybe something like a | or • could work?
