### ISSUE TITLE
[Bug] Party member icons draw on maps other than one player is in

### ISSUE THREAD

**Issue by NadyaNayme** [MidoriKami/Mappy#126]
Minor aesthetic issue but filing it anyways. It doesn't bug me any because really how often am I looking at another map w/o the intentions of going to that map at least? 

Reproduction steps:

1. Be in a party
1. Open a different map (eg. Search and open any map) 

![image](https://github.com/user-attachments/assets/86a75a8d-ef2f-4cdd-bc1c-afd2313a3b74)

Expectations: 

- Map doesn't draw party icons when map is not the location the player is currently in.

Not sure if being in a party matters might happen for the player's dot I'll test later and report back. Not leaving my party ATM.

**Comment by MidoriKami** [comment]
Untested, but don't see why it wouldn't work
