### ISSUE TITLE
[Bug] Hunt mark bills don't show location if map is closed

### ISSUE THREAD

**Issue by MonoCoal** [MidoriKami/Mappy#127]
If map is closed, then on first click on the bills it shows player's current location. After pressing second time, while map is opened, it shows location correctly. Playing on controller it's hard to press it twice.

https://github.com/user-attachments/assets/c7f5f88f-b8fd-4d84-a10e-8998cc8c3892

**Comment by MidoriKami** [comment]
I consider this to be related to #86

**Comment by MidoriKami** [comment]
Unfortunately due to the complexity of the systems involved, and my limited time, I am considering this a wontfix for now.
