### ISSUE TITLE
Quest icons not updating to current map/quest step when map changes due to cutscene

### ISSUE THREAD

**Issue by Xanieros** [MidoriKami/Mappy#134]
Just changed from Tuli to Shaaloani during a cutscene and the quest marker locations and triple triad icons are all from Tuli. The msq marker is stuck on the step which pulled me to Shaaloani. This is during the quest In Yyasulani's Shadow after talking to Wak at the Skybridge. Problem is resolved if I search for another map and then come back to the current map. All other icons like vendors and aetherytes were all correct for the Xak map. Last thing, the Fates were also missing before I refreshed the map.

**Comment by MidoriKami** [comment]
Complex issue not likely to be fixed soon

**Comment by MidoriKami** [comment]
Topic moved to #150
