### ISSUE TITLE
[Bug] Question Mark Icons on Tribal Quest Locations

### ISSUE THREAD

**Issue by Dukmos** [MidoriKami/Mappy#14]
This happens for me with the Vanu Vanu and Moogle Tribal Quests (but that are the only ones I did after installing Mappy)

![image](https://github.com/MidoriKami/Mappy/assets/1273625/15bb2d74-2cc6-4ebf-9734-0c563ba9bbd5)

If its not an Area it works as intended and shows the correct Icon

also, the Circles are a different size then on the normal Map

**Comment by MidoriKami** [comment]
Working as intended.
