### ISSUE TITLE
[Request] A way to open local maps

### ISSUE THREAD

**Issue by promexahnk** [MidoriKami/Mappy#140]
There is, currently, no way to open the local territory map unless you go there or navigate using map markers

**Comment by MidoriKami** [comment]
No idea what you're referring to.

**Comment by promexahnk** [comment]
In the original XIV map, if you open the region map, you can then from there open an individual local zone map just by pressing an outline of the map:
![ezgif-3-4846e7adfa](https://github.com/user-attachments/assets/65cf4566-8cd3-40f9-9b60-3a2c0647baa9)

**Comment by MidoriKami** [comment]
Ah, not planned.
