### ISSUE TITLE
[Bug] Draw options for player cone not working

### ISSUE THREAD

**Issue by DormantLime** [MidoriKami/Mappy#144]
Before DT launched I was able to change the colors of my Player Cone- since the update, it appears to display the wrong default colors (gray), and does not update any colors when you change them. I'm attaching a couple of screenshots. 
![Screenshot 2024-07-24 115520](https://github.com/user-attachments/assets/a9bf5cc9-7247-4219-aff3-68eed4166539)
![Screenshot 2024-07-24 115535](https://github.com/user-attachments/assets/8a1e4ea8-6374-48a3-96e1-dc4daea40b07)

**Comment by MidoriKami** [comment]
Radius is not cone. Increase the alpha of the radar to see this.
