### ISSUE TITLE
REQUEST: Follow player keyboard shortcut

### ISSUE THREAD

**Issue by chrispysaid** [MidoriKami/Mappy#147]
Title says it. Would be good to have an assignable keyboard shortcut to toggle Follow Player rather than having to click it every time.

**Comment by MidoriKami** [comment]
Good idea

**Comment by nightpanda2810** [comment]
To add to this, I use a stream deck for some stuff, having some / commands for some of these toggles would be fantastic.

**Comment by MidoriKami** [comment]
> To add to this, I use a stream deck for some stuff, having some / commands for some of these toggles would be fantastic.

Please make a seperate issue for this

**Comment by nightpanda2810** [comment]
> > To add to this, I use a stream deck for some stuff, having some / commands for some of these toggles would be fantastic.
> 
> Please make a seperate issue for this

Done!

**Comment by MidoriKami** [comment]
Implemented commands here (42d5a2e05c926797b2fb242614051cc56590d28a), recommended approach is to put it in a vanilla macro and place it on a hotbar

**Comment by chrispysaid** [comment]
Thanks! I'm not sure what that means, I don't read code or develop stuff. What am I meant to do?

**Comment by nightpanda2810** [comment]
> Thanks! I'm not sure what that means, I don't read code or develop stuff. What am I meant to do?

Just need to wait for the plugin to be updated in Dalamud.
