### ISSUE TITLE
Links From Quests Not Showing Correct Location

### ISSUE THREAD

**Issue by uberdragon** [MidoriKami/Mappy#149]
There seems to be a bug when attempting to pull up map locations using quest links see screen shots below:

Example of a quest link 
![Screenshot 2024-07-25 at 6 42 20 PM](https://github.com/user-attachments/assets/b26407a6-bcaa-45d9-b315-5fd3ecf13cc4)

Example of default map - Which then let's you click on the location to drill down into next map
![Screenshot 2024-07-25 at 6 42 31 PM](https://github.com/user-attachments/assets/31e28be9-f50b-4970-97e2-51e7ab2ae176)

Where Mappy goes after clicking the quest link:
![Screenshot 2024-07-25 at 6 43 13 PM](https://github.com/user-attachments/assets/55f228ca-afc6-47f2-9880-076ef98785b9)

**Comment by uberdragon** [comment]
It's not all quest links either.  Just the ones where the default map loads that zoomed out map shown in my example.

**Comment by MidoriKami** [comment]
Topic moved to #150
