### ISSUE TITLE
[Bug] Cross-mod issue with Gatherbuddy - flag and gather-zone markers not appearing correctly

### ISSUE THREAD

**Issue by PrincessRTFM** [MidoriKami/Mappy#15]
When I used GB's `/gather` command, it correctly sets my map's marker location and opens Mappy's map, but the flag marker and the gathering zone circle marker do not show up. Even if I close and reopen the map, it still doesn't see the map marker, even if it was in the current zone and is thus visible on my minimap. Once I click the location link, Mappy renders the flag marker. If I reuse the same `/gather` command, the circle and flag markers are both rendered correctly. The main issue is the map flag marker, since that's the easiest way to find the gathering nodes.

I'm not sure if there's anything else I can provide that would help, like my configuration files. Let me know and I'll do whatever I can.

**Comment by MidoriKami** [comment]
Initial findings, due to the marker being placed first and then the map being opened, Mappy guesses that the marker should be in the currently displayed zone.

I may be able to work around this if I assume that every SetGatheringMarker call will be followed by an OpenMap call.

**Comment by PrincessRTFM** [comment]
I found a possibly-related issue with TinyCommands clearing the flag on `/clearflag` and Mappy still rendering the marker, even after closing and re-opening. Should I make a new issue for that?

**Comment by MidoriKami** [comment]
Yes that's a separate issue
