### ISSUE TITLE
[BUG] Quests Don't do the Thing Correctly

### ISSUE THREAD

**Issue by MidoriKami** [MidoriKami/Mappy#150]
This issue is a super post for all the various posts people are making thinking they are unrelated when they aren't.

Please do not make any new posts related to quests, instead comment on this post.

**Comment by MidoriKami** [comment]
related to #149

**Comment by MidoriKami** [comment]
related to #134

**Comment by MidoriKami** [comment]
related to #86

**Comment by Zerkhan2791** [comment]
As a follow-up to the above. Using Mappy's fates list window, the map repositions correctly to the flags placed by interacting with the fates from the list (where flag marking is enabled). Appologies if this has already been fixed and not released.

**Comment by axium1998** [comment]
Pretty sure this has occurred with the latest update, but clicking on quests to show the location places the marker on the map the quest originates from and not where the destination is (both quests are from ARR)

![image](https://github.com/user-attachments/assets/e7d0a6b3-9c07-4a0f-86db-a897535eb645)
![image](https://github.com/user-attachments/assets/1984512b-b4c9-401d-87dd-5b9f9aaa2f61)

**Comment by MidoriKami** [comment]
> Pretty sure this has occurred with the latest update, but clicking on quests to show the location places the marker on the map the quest originates from and not where the destination is (both quests are from ARR)
> 
> ![image](https://private-user-images.githubusercontent.com/4612427/352784525-e7d0a6b3-9c07-4a0f-86db-a897535eb645.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMzQxNTAsIm5iZiI6MTcyMjEzMzg1MCwicGF0aCI6Ii80NjEyNDI3LzM1Mjc4NDUyNS1lN2QwYTZiMy05YzA3LTRhMGYtODZkYi1hODk3NTM1ZWI2NDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMDIzMDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdmMmExNGUzYmQzNTkxZTYxZDAwOGU0MDhhMTQzNTIyN2QxYmRjOTYxZDg4NzkyODJmZDhiMDQ2YzYwMjMzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mTWLdTePUQ9ItWJL3lyDoSJS4l9HcI9UP_t18YIFBuw) ![image](https://private-user-images.githubusercontent.com/4612427/352785777-1984512b-b4c9-401d-87dd-5b9f9aaa2f61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMzQxNTAsIm5iZiI6MTcyMjEzMzg1MCwicGF0aCI6Ii80NjEyNDI3LzM1Mjc4NTc3Ny0xOTg0NTEyYi1iNGM5LTQwMWQtODdkZC01YjlmOWFhYTJmNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMDIzMDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjg2ZjQ1YzFlZmJkYTk3OTZmMTMzZTk1NWU3OTI3ODVjZDkyYTdhOTViOGE4MzFlMWRlZThlMTE0MTRiYWNiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QksovSOk9svTLzaxKQ1lqs37ppQ6WdlR81yMEyiUKAg)

This one I did find myself as well, not sure how to address it because it's defined as a "TemporaryMapMarker" in the game data, and doesn't have any information about what map it is supposed to be drawing on.

**Comment by AikoTM** [comment]
Just gotta add this Quest with the same issue.
Clicking on "Map" in the Journal opens up the Map from Living Memory instead of Solution 9. 
There is a Quest-step in Living Memory, but the Quest is accepted in Solution 9 so the former statement of "Opens up the Map the Quest originates from" does not apply in this case. 
This is with Mappy v3.0.1.4

I had the same issue with the Level 99 Hunting Board quest yesterday btw. I forgot the name...
It opened up the Map of Solution 9, instead of Tuliyollal.
Curious but so far I only encountered the issue when the Quest is finished aka. ready to be turned-in. 

![grafik](https://github.com/user-attachments/assets/e6a9e716-eb72-41c4-8894-d6dcb14447d3)

**Comment by Atroskelis** [comment]
On the Hunt, seems to have an issue with reaper HQ as it happened at the start and at the end of the quest. The icons are also duplicated

The points do not move from their position when viewing wrong city
The point was corrected to the entrance in reaper city

![image](https://github.com/user-attachments/assets/d806426f-316d-44c9-8ded-1c095e007dc9)

**Comment by MidoriKami** [comment]
I just want to thank all of you for continuing to post data to this issue. I haven't really had much time to investigate myself, and having all this data has already helped narrow down potential causes. Please continue to post any information you come across.

**Comment by Atroskelis** [comment]
I cannot escape the feeling that it doesn't properly handle either succesive map changes or inside/outside of interior spaces

Here in the screenshot upon map click it showed me the inside of reaper HQ, but when i clicked the arrow to go outside, the icons duplicated. The blue is the same as the icon on the right. 

![image](https://github.com/user-attachments/assets/29fca551-dca8-4f07-85b9-272e07de7282)

**Comment by MidoriKami** [comment]
potentially fixed by f60ee2560e0edaa7bea59c1b0696d57c65e63b91 and 44f147a11761e886b968ca21aab2dea71b9597b3 and 5b444aaf10cc243db132590071cfdf5000d21baf

**Comment by Atroskelis** [comment]
Groping in the Dark,

Mappy v3.0.3.4

This quest involves 2 maps of closed spaces,  the icons overlap with the other map.
Basically inside both maps you see points of either maps. But only the action points not the map-travel points

![image](https://github.com/user-attachments/assets/809456b4-9f90-4397-b638-9318f30066c7)

**Comment by k8thekat** [comment]
Not sure if this is intended or not. But if you enable "Follow On Open" and pick "Player" the map will no longer open to quest objectives and will always open to the current map the player is on despite clicking the "map" button inside quest logs or on the quest list hud.

**Comment by MidoriKami** [comment]
> Not sure if this is intended or not. But if you enable "Follow On Open" and pick "Player" the map will no longer open to quest objectives and will always open to the current map the player is on despite clicking the "map" button inside quest logs or on the quest list hud.

Please create a new issue, this thread is no longer relevant, that's why it's closed.
