### ISSUE TITLE
[Bug] Radar color options not working

### ISSUE THREAD

**Issue by kachx** [MidoriKami/Mappy#152]
Just stays grey no matter what.

Default
![image](https://github.com/user-attachments/assets/54d31b27-d503-4e9d-86d8-037a62f9f289)

Colors changed
![image](https://github.com/user-attachments/assets/17a11102-7e49-4bce-bb5e-f8bf6846d97d)

Tried restarting, the colors are properly saved in the settings but the radar stays grey.

**Comment by MidoriKami** [comment]
Already fixed in 29b77f6775468b4c91d207a75c72df4d185eaf63
