### ISSUE TITLE
[REQUEST] Add residential district housing numbers under each house

### ISSUE THREAD

**Issue by TypicalTooley** [MidoriKami/Mappy#154]
Have the map display associated housing numbers for each house. Hard to find houses I am looking for without the number being displayed.

**Comment by MidoriKami** [comment]
Planned jus haven't have the time to work out how to do it in a same way.

**Comment by TypicalTooley** [comment]
That's such a relief! And under the same category while I am here, tho I am done with my hunt log but for future users. During my time searching for areas I needed translation for that are written on the map in Eorzean would have been far faster if there was a mouse over area text. Love the work you've done man.

**Comment by MidoriKami** [comment]
Marking as duplicate #131
