### ISSUE TITLE
Map blanks when moving or unfocused

### ISSUE THREAD

**Issue by Jake-Jensen** [MidoriKami/Mappy#159]
Version: v3.0.1.4
Installed via Dalamud Plugin Installer
Nothing modified, nothing changed

When standing still, the map operates correctly, but when unfocused, or while moving, the map disappears, leaving just the window itself open. Attached is a video showing the problem. 

https://github.com/user-attachments/assets/79b6352a-4af6-44ba-b53d-e94a9bc59722

**Comment by MidoriKami** [comment]
Your Fade Opacity setting is set to `0.000` and you have Fade : `When Moving` enabled.

**Comment by Jake-Jensen** [comment]
This is a default install on a fresh install of W11; Are these settings default now?

**Comment by MidoriKami** [comment]
Default settings are as follows:
```cs
    public float FadePercent = 0.60f;
    public FadeMode FadeMode = FadeMode.WhenUnFocused | FadeMode.WhenMoving;
```

My UI Element for changing the fade doesn't let you go below `0.05`, so it's possible your config file got mildly corrupted, I recommending running some kind of HDD error checker.
