### ISSUE TITLE
[Request] Make the map window ignore escape keypresses

### ISSUE THREAD

**Issue by PrincessRTFM** [MidoriKami/Mappy#16]
Sometimes when I try to close a vanilla window with escape, Mappy's window receives the keypress instead and closes when I didn't want it to. It would be nice if it no longer did this, or if the "keep open" option _didn't_ block using the "open map" keybind to close the window, so that the map can stay open until explicitly closed.

**Comment by MidoriKami** [comment]
I'm very hesitant to modify any existing behavior, but I can provide a toggle to disable escape to close in the general options.

**Comment by PrincessRTFM** [comment]
That's actually what I'd prefer, thank you!
