### ISSUE TITLE
[Feature Requests] Various UX/UI requests

### ISSUE THREAD

**Issue by kasuriax8** [MidoriKami/Mappy#164]
Hello, awesome work! Would it be possible to incorporate any of the following?

### Player Tab
1. **Cone Options**: Orient to player/camera, player direction instead of camera direction (current).

### Style Tab
1. **Window Options**: 
**Show Window Frame** on Hover or when holding a hotkey (shift?). Hiding the window frame is awesome, keeping Mappy's footprint minimal on screen however if I need to move it out of the way, I can't without toggling this in the settings
2. **Area Style**
**Outline**: On/Off options or color options. Currently I cannot set the thickness, I would rather have it off because it is too much noise...

### Map Functions Tab
**Zoom Options** Zoom in point Cursor, player, map. Currently it is zoom in relative to map, I think it's more standard to zoom in on cursor location or on player
**Ctrl + Right click**: right click opens the context menu which is awesome but I lost my ability to place flags easily via ctrl right click which is the biggest reason apart from seeing the zone, this has turned from one action to 2 actions w/ Mappy. I just noticed that i can right click then left click immediately to place a flag but that may be due to my Dalamud grab padding being higher than 0

**Comment by MidoriKami** [comment]
> Cone options 

No.

> Window Frame

Instead I may make it move the window when holding shift and dragging.

> Areas

I will not allow disabling areas, they are a core function of the game.

I may add border thickness options.

> Zoom

The math to make zoom on cursor work is a serious pain in the ass and I simply don't have the free time to do it.

If someone wanted to PR that to Mappy it would be welcomed.

Zoom on player I am not interested in.

> Context menu

No.

**Comment by kasuriax8** [comment]
>Window Frame
agreed, shift dragging does sound better

> Areas
I did not mean disabling areas outright. I wanted the ability to remove the outline but changing the border thickness would be nice as well. 

I have opened a PR #165 pertaining to Areas and Player Cone color/outline color

**Comment by MidoriKami** [comment]
Implemented by #165 and #166
