### ISSUE TITLE
[Request] "Centre map in window" feature

### ISSUE THREAD

**Issue by PrincessRTFM** [MidoriKami/Mappy#17]
There's a button to centre the map on the player, but it would be nice if there was also a button to centre the map on the middle of the zone, in order to be able to see the whole area including yourself and the various markers. I commonly use this kind of positioning to look for FATEs and quests within a single zone.

**Comment by MidoriKami** [comment]
What FontAwesome icon would be most fitting for this?

You can view all icons in `/xldata` under `FontAwesome Test`

**Comment by MidoriKami** [comment]
Additionally, You'd want it to zoom out to try and fit the map on the screen?

**Comment by PrincessRTFM** [comment]
That'd be fantastic if you did that! But either way, I'm not overly picky.
