### ISSUE TITLE
[Suggestion / Request] Load map replacers loaded by Penumbra

### ISSUE THREAD

**Issue by HawkAtreides** [MidoriKami/Mappy#170]
Is it possible to have Mappy load the maps in whatever way Penumbra replaces them rather than displaying the vanilla map or making me use TexTools to overwrite game files? I currently use a hunt-mark map replacement modpack that works on the vanilla map when loaded via Penumbra, but doesn't work in Mappy. If I load the files with TexTools, they'll work in Mappy, but it seems like everyone's trying to move away from doing things that way.

**Comment by MidoriKami** [comment]
Duplicate #97
