### ISSUE TITLE
Latest updates incompatible with Annotated Maps/Any Map Mods

### ISSUE THREAD

**Issue by BlackWyvern** [MidoriKami/Mappy#172]
Seems to be an issue wherein any mod that changes the map files fails to load completely.

Mappy used to be compatible with [Annotated Maps](https://github.com/RKI027/ffxiv-huntmaps/releases) but these last few updates have caused Mappy to show blank, (or completely fail to remain open if window frame is hidden), if trying to display one of the changed regions.

Previous version still had DT field locations loading and working. Confirmed it's a system-wide issue when I updated the mod to DT and now all maps outside of cities fail to load.

**Comment by MidoriKami** [comment]
Already addressed in fda15cf3a19c6befe365700d9279ce63584c6ed1

**Comment by MidoriKami** [comment]
Currently it requires any mods to replace both the foreground texture and background texture. A future version will no longer require both to be replaced.

**Comment by Sidiousious** [comment]
@MidoriKami is there any word on when this future version might happen? The lack of compatibility with [Hunt Maps](https://github.com/RKI027/ffxiv-huntmaps) is keeping me from using Mappy.

**Comment by MidoriKami** [comment]
> @MidoriKami is there any word on when this future version might happen? The lack of compatibility with [Hunt Maps](https://github.com/RKI027/ffxiv-huntmaps) is keeping me from using Mappy.

Try it. It works now. Not sure what compatibility issue you are referring to this post is months old and no longer relevant.

**Comment by Sidiousious** [comment]
Vanilla map shows the modded texture. Mappy does not. This issue seemed relevant. Apparently not? I haven't a clue how texture replacements work in the game beyond my ability to install them.
