### ISSUE TITLE
[bug] tempered npc icon size

### ISSUE THREAD

**Issue by hhharkness** [MidoriKami/Mappy#173]
tempered swords and brands in southern thanalan are showing up huge
![image](https://github.com/user-attachments/assets/fb6447e2-d9ab-442f-8d68-9bd6e964723d)

**Comment by MidoriKami** [comment]
Nice.

I'll take a look tonight.

**Comment by MidoriKami** [comment]
fixed in 5ef0547516252825ef82f897ba6e09a3dc9054fa
