### ISSUE TITLE
[Request] Click navigation in region maps

### ISSUE THREAD

**Issue by AlphaLion13** [MidoriKami/Mappy#176]
Good day. My request is to be able to click, either on the whole area, or a pin (like in the continent map) to enter into a map layer.
Using the debug mode, I can see that the areas are already delimited,
![image](https://github.com/user-attachments/assets/4c70131e-ae17-4db0-bb36-198268d7da53)
I ask for an option to click on that area and enter the respective map
![image](https://github.com/user-attachments/assets/eee821ca-dc02-43dc-9516-423c1477a142)

Although the option to do it already exists in the form of layer changing, I find it a lot more cumbersome than simply clicking on where I want to go, and another problem, that may need the opening of another issue as a bug, is that not every map has it's layers set properly
![image](https://github.com/user-attachments/assets/3881b0f7-af52-415d-9557-eb97bc32e370)
The Othard region map doesn't have any layers, so the only way I can enter the more detailed maps is if I have a quest in them already, and use them as shortcuts to the map.

Thank you for making the plugin, I hope I could explain my problem well enough.

**Comment by MidoriKami** [comment]
There is no reasonable way to accomplish this.
Due the the overlap of the textures, there's no reasonable way to know which map you are selecting.

Please open a different issue documenting which maps don't support layers to navigate.
