### ISSUE TITLE
Huntmaps texture does not show up in Mappy

### ISSUE THREAD

**Issue by Sidiousious** [MidoriKami/Mappy#179]
Using https://github.com/RKI027/ffxiv-huntmaps/releases I cannot see the modified map textures within Mappy, but I can see them within the game's normal map. #172 would suggest this should work.

Without Mappy:

![image](https://github.com/user-attachments/assets/52f7ce79-c9c8-4c77-90d8-de202dd6b223)

With Mappy:

![image](https://github.com/user-attachments/assets/3b99a57d-182c-4dea-a380-3f505cb5d3ae)

I would expect the modified texture with the pink and red dots to be shown within Mappy.

Mappy logs:

```
05:39:37.984 | DBG | [Mappy] Enabling Integrations
05:40:46.217 | DBG | [Mappy] [OnShow] Beginning Show
05:40:46.221 | DBG | [Mappy] [OnShow] Called Original with A1 = True, A2 = False
05:41:33.769 | DBG | [Mappy] [OpenMap] Called Original with MapInfo [ MapId: 696, MapType: Centered, Title: , PlaceNameId: 0, AetheryteId: 0, FateId: 0, Unknown 1C: 0, Unknown 88: 0, Unknown 8C: 0, Unknown 8D: False ]
05:41:33.769 | DBG | [Mappy] [OpenMapById] Called Original with MapId = 696, A3 = 0, A4 = True
```

**Comment by MidoriKami** [comment]
![image](https://github.com/user-attachments/assets/50272f62-0979-4433-9957-45ec4024bbd8)

Unable to reproduce issue.

**Comment by Sidiousious** [comment]
Fair enough, seems like a me issue then. [Ended up building my own version that reads directly from my penumbra folder instead.](https://github.com/user-attachments/assets/5a519e6d-bb78-42d5-a5b6-776d3c20ccd6) Hacky, but I guess it'll do for me.

**Comment by MidoriKami** [comment]
You likely have the mod configured incorrectly in penumbra, it has to be a part of the interface collection I think? I don't really know the cause of your issue, it's not caused by Mappy itself, as I was able to import the mod that you linked and have it just work immediately.
