### ISSUE TITLE
[Request] Arrow around window edges for Icons out of view.

### ISSUE THREAD

**Issue by SeanKR-IRE** [MidoriKami/Mappy#180]
Although I understand Mappy isn't a replacement for a minimap, I still feel this could be a handy feature for some.

One feature I found super useful especially with having Follow Player enabled was the icons showing as an arrow on the edge of where they are. I don't personally like having the map super zoomed out when follow is toggled. 
An example in-game being the map marker being just off the minimap showing on the rim of the minimap.

![image](https://github.com/user-attachments/assets/1e383a81-e35a-4386-94df-656de61e1679)

Not all icons need this feature of course. All could have the feature with a checkbox in the settings "Icon Settings" to allow for user customization. By default all disabled since most likely be cluttered especially when zoomed in.

**Comment by MidoriKami** [comment]
I'm not interested in implementing such a complicated feature at this time.

I might consider accepting a PR if someone wanted to contribute this feature.
