### ISSUE TITLE
[bug] teleportation sending chat message

### ISSUE THREAD

**Issue by hhharkness** [MidoriKami/Mappy#183]
ever since the 7.1 update whenever i teleport by clicking an aetheryte on the map it prints a log message, even with show chat messages unchecked in teleporter. this does not happen when using commands to tp so it seems to be a mappy issue

**Comment by MidoriKami** [comment]
Mappy no longer uses teleporter to do teleports and teleports using its own code.
This is working as intended, and I have no intention of offering a toggle to disable the message.
