### ISSUE TITLE
Dalamud UI global font scaling breaks search window drawable selection window

### ISSUE THREAD

**Issue by TommyDi7** [MidoriKami/Mappy#184]
![Screenshot 2024-11-24 115823](https://github.com/user-attachments/assets/17342e4e-5572-47e4-a05a-9022f22755dd)

The window breaks due to the image scales with global font scale (but not the font size), I have a 4k monitor and needed the font scaling to read anything.

Maybe add an option to remove the image from the search window or allow the window to resize?

**Comment by MidoriKami** [comment]
Related to:
https://github.com/MidoriKami/SortaKinda/issues/36#issuecomment-2495806359

Both plugins use the same library for rendering selection windows.

**Comment by MidoriKami** [comment]
Self reminder, create attribute to properly name drawable options.
