### ISSUE TITLE
[Bug] Deep Dungeon/V&C Dungeon label shows br tag

### ISSUE THREAD

**Issue by kachx** [MidoriKami/Mappy#186]
![image](https://github.com/user-attachments/assets/385b430d-107e-4ad8-a630-5b82f3bdd444)

![image](https://github.com/user-attachments/assets/0ca50029-6919-4352-a4a6-1091a94fbabd)

Not sure what else to write about this

**Comment by MidoriKami** [comment]
Due to the lumina changes internally they changed how .tostring works for game data. These calls to .tostring need to replaced with calls to .extracttext
