### ISSUE TITLE
[Suggestion] Region List

### ISSUE THREAD

**Issue by Dracoman13** [MidoriKami/Mappy#189]
One bit of functionality that I miss from the vanilla version of the map is being able to zoom out and eventually select from a list of regions all the way from ARR to DT. The search function is nice, but I just like a nice list, plus having things in release order helps me parse through them all.

**Comment by MidoriKami** [comment]
I'm not actively playing the game and am not currently accepting feature requests.

The layout of the games data also makes this a rather difficult task to do, or I would already be a part of Mappy.
