### ISSUE TITLE
[Suggestion] For the quest marker circle not being solid blue

### ISSUE THREAD

**Issue by dragonzxzz** [MidoriKami/Mappy#190]
Hi, in the original map it's a light orange circle area that you can see through.
and on mappy it's a non-see through blue circle
![image](https://github.com/user-attachments/assets/0568a19c-3578-423e-bff5-6a521e8d9298)
 If possible, would like to have an option to have it see through or color options like some other settings.

**Comment by MidoriKami** [comment]
Option already exists, set the A value to something non zero.
