### ISSUE TITLE
[Bug] Job Quest AOE location

### ISSUE THREAD

**Issue by WesBosch** [MidoriKami/Mappy#23]
![image](https://github.com/MidoriKami/Mappy/assets/63926174/d8778f4d-6a96-475c-809b-9a9c2b22024a)
The quest marker near me is for this Job quest (DRK Quest Heroic reprise), but theres a DRK bubble up near the center of the map too for some reason. (flag was added myself to see if it was unusual coords like 0, 0 or something) Job included a solo instance in a lower part of the map, but never went to this area. Icon appears otherwise fine in Foundation, Still leveling this class, so I should have more opportunities to test if other quests behave this way later

![image](https://github.com/MidoriKami/Mappy/assets/63926174/e482896d-e10e-44fe-8aca-82352e77d59f)

**Comment by MidoriKami** [comment]
**potentially** fixed in 00425d62f4ddee5fbf04c77c2368e1928d161ec4
I will close this issue for now, if it occurs after the next Mappy update, then re-open this issue.
