### ISSUE TITLE
[Request] Adding Support for zooming in while dragging

### ISSUE THREAD

**Issue by AtIgnister** [MidoriKami/Mappy#26]
As far as i can tell, mappy currently doesnt let you zoom into the map while dragging the map viewport around. It would be nice to have the option to zoom in while doing that. Right now, it feels a bit awkward to zoom in on a location as you have to first drag the view to that location, then stop dragging and start zooming in.

**Comment by MidoriKami** [comment]
I'll consider it, no promises.

The input system is relatively complex to be as intuitive as it already is.

**Comment by MidoriKami** [comment]
This feature does not and will not zoom into where your cursor is, so while dragging if you use your mousewheel it'll zoom in on whatever was in the center of the viewport at the time.
