### ISSUE TITLE
[Bug] Quest markers missing during "Agriculture Shock"

### ISSUE THREAD

**Issue by Story-Collector** [MidoriKami/Mappy#28]
During the Endwalker quest "Agriculture Shock", on the map "Labyrinthos", most of the quest markers are missing. The initial quest marker appeared, to pick up the quest, but none of the usual question mark icons appeared, nor MSQ quest markers. The end of quest Green checkmark MSQ icon did appear, however, and no further issues were observed.

Steps taken: 
Toggling on/off the plugin did not solve issue
Made sure plugin was up-to-date with Dalamud Plugin Installer "Update Plugins" button
Uninstalled and reinstalled Mappy - issue still persisted during quest.
Did not attempt full restart of game, as issue cleared upon quest completion.
Quest icons appeared normally on vanilla mini-map

This appeared on Mappy version 1.0.1.0

**Comment by MidoriKami** [comment]
Try to reproduce in v1.0.1.1
