### ISSUE TITLE
[Request] Player Cone Radius that doesn't scale with zoom

### ISSUE THREAD

**Issue by k0etsu** [MidoriKami/Mappy#29]
Small behavior "issue" that I noticed in that the player cone radius scales with zoom whereas none of the other icons drawn on the map seem to behave the same way.

**Comment by MidoriKami** [comment]
Intentional design decision.

**Comment by MidoriKami** [comment]
You're welcome to argue why you think it should be changed, but as of right now I see no reason to make the view cone stay constant size.

**Comment by k0etsu** [comment]
My viewpoint is that the vanilla map does not adjust the view cone when zooming in/out. Addtionally, having the cone visible when zooming out on the map makes it easier to see at a glance/with peripheral which direction you are facing without messing with the configuration or zooming in.

However, I also acknowledge that you have already mentioned up front that Mappy is not intended to be a minimap replacement which I admit that I do so not something that I am super stressed about.

If this ultimately isn't implemented, anyone in the future that wants to compile on their own can simply remove the scaling factor when drawing the cone:

`var lineLength = config.ConeRadius; // * mapWindow.Viewport.Scale;`
