### ISSUE TITLE
[Feature Request] Penumbra compatibility

### ISSUE THREAD

**Issue by thakyZ** [MidoriKami/Mappy#3]
I would like to request a feature. This would be loading maps that are changed via Penumbra so that there can be hunt marks, and other things like accessibility via mono-chroming the maps.

**Comment by MidoriKami** [comment]
6e7e0c8340d16a02eeedcdf3924ca64c52f9d091 closes #3

**Comment by MidoriKami** [comment]
Compatibility is added. I will not be adding additional penumbra related features.
