### ISSUE TITLE
[Request] Map automatically zooms in a lot when opening from a clicked location link

### ISSUE THREAD

**Issue by PrincessRTFM** [MidoriKami/Mappy#30]
Every time I open the map from a location link, it's zoomed in very far and I always have to zoom it out quite a bit to see _where_ the location actually is in the zone. Is it possible to make the map not change zoom when targeting a linked location?

**Comment by MidoriKami** [comment]
Option to disable zoom was already added in v1.0.1.1
fb9ae997528cd49bdaf4f9b489c727f267918c08
