### ISSUE TITLE
[Bug] Lifestream does not pick up Aethernet clicking

### ISSUE THREAD

**Issue by TheOddball** [MidoriKami/Mappy#32]
Title. There's a plugin called [Lifestream](https://github.com/NightmareXIV/MyDalamudPlugins/blob/main/pluginmaster.json) that I use frequently, which has support for auto teleporting to an Aethernet that you click on the vanilla map. However, while using Mappy, this functionality does not work.

**Comment by MidoriKami** [comment]
I do not provide any direct support for custom repo plugins. Mappy integrates with the "Teleporter" plugin use that instead.
