### ISSUE TITLE
[Request] In-game way to add markers

### ISSUE THREAD

**Issue by PISTOLCUPCAKES** [MidoriKami/Mappy#33]
Is it possible to add an in-game option/way to add markers? The documentation mentions there are functions available for other plugins to do this but it would be nice if this was possible to do directly in mappy itself.

**Comment by MidoriKami** [comment]
Why?

**Comment by PISTOLCUPCAKES** [comment]
I mostly want it for marking gathering nodes. I'm sure there are other use cases - why even have the API for other plugins to create markers?
