### ISSUE TITLE
[Request] Height relative icons for quests

### ISSUE THREAD

**Issue by k0etsu** [MidoriKami/Mappy#34]
Was wondering if it were possible to add layered icons if z-axis exceeds a certain threshold for quest locations (zone/npc).

**Comment by MidoriKami** [comment]
Please clarify your remark and provide pictures if applicable.

**Comment by k0etsu** [comment]
Image provided:

![image](https://github.com/MidoriKami/Mappy/assets/7014583/ed9d9de1-21ec-4762-928d-4d5efe25f9f7)

**Comment by MidoriKami** [comment]
> Current quest icon sets do not indicate any height difference when viewing map (as far as I am aware).

There are no other icon sets the game uses, they are drawing the arrow marker ontop of the icon.

**Comment by k0etsu** [comment]
I will take a look just as a personal interest in learning but this can probably be closed in that case.
