### ISSUE TITLE
[Bug] Hiding Quest Icons leaves Directional Markers behind

### ISSUE THREAD

**Issue by Dukmos** [MidoriKami/Mappy#36]
when hiding a Quest icon with a Directional Marker it stays behind

with Sidequest Icon enabled
![image](https://github.com/MidoriKami/Mappy/assets/1273625/7c67e4f5-9670-45e9-9cf7-ecd11cdda738)

with Sidequest Icon hidden
![image](https://github.com/MidoriKami/Mappy/assets/1273625/aa8ea840-e7fd-4098-9dde-fb414a2aa4a0)

**Comment by hsramm** [comment]
I was just coming back here to report this. Thank you!
