### ISSUE TITLE
[Bug] NG+ quests markers don't show up on the map

### ISSUE THREAD

**Issue by CharlieDelune** [MidoriKami/Mappy#39]
Pretty much the title. If you initiate NG+ mode, quest icons for picking up quests, turning in quests, talking to people, or going to an area, don't show up on the map. Clicking on the quest text will still open the map in the correct position, there are just no markers.

**Comment by NineNates** [comment]
Can attest to this affecting non-NG+ too, at least in some cases, such as mine. Likely something to do with 6.48.
