### ISSUE TITLE
[Bug] Issue with the toolbar not showing

### ISSUE THREAD

**Issue by krz0001** [MidoriKami/Mappy#4]
When logging in with my main character, the toolbar doesn't show up.
`/xllog` gets a lot of exceptions like the one below. (My main character currently has 8 levequests accepted.) 
![image](https://github.com/MidoriKami/Mappy/assets/18511031/2f0b71e4-208a-41d4-83c2-589f9e0d5a3d)

When logging into my alt that doesn't have any levequests accepted, the toolbar shows up without any issue.

**Comment by MidoriKami** [comment]
Where is your main character located, what zone, and what coordinates, and can you list the accepted levequests please.

**Comment by krz0001** [comment]
My main character is in Radz-at-Han, X: 11.8 Y: 10.4 - accepted leves are:

1. [Salt of the North](https://ffxiv.gamerescape.com/wiki/Salt_of_the_North) lv. 80
2. [Bobbing for Compliments](https://ffxiv.gamerescape.com/wiki/Bobbing_for_Compliments) lv. 82
3. [At Any Temperature](https://ffxiv.gamerescape.com/wiki/At_Any_Temperature) lv. 82
4. [A Stickler for Carrots](https://ffxiv.gamerescape.com/wiki/A_Stickler_for_Carrots) lv. 84
5. [Imperial Palate](https://ffxiv.gamerescape.com/wiki/Imperial_Palate) lv. 84
6. [Comfort Food](https://ffxiv.gamerescape.com/wiki/Comfort_Food) lv. 86
7. [An Historical Flavor](https://ffxiv.gamerescape.com/wiki/An_Historical_Flavor) lv. 86
8. [Blast from the Pasta](https://ffxiv.gamerescape.com/wiki/Blast_from_the_Pasta)	88

**Comment by MidoriKami** [comment]
Even included links, awesome, this will take some time to track down.

**Comment by MidoriKami** [comment]
Bug was specific to tradecrafts as tradecrafts have no defined start position.
