### ISSUE TITLE
[Feature Request] Controller integrations

### ISSUE THREAD

**Issue by Tyrannical-Potato** [MidoriKami/Mappy#4]
Any chance controller integrations could be added? (such as holding L1 and tapping R1 to place a flag)?

**Comment by MidoriKami** [comment]
I will not be adding controller features. Writing code for controller features as a person that never plays with a controller is extremely stressful for me.

If someone wants to PR controller integrations I'll happily approve and merge it. I won't approve a interaction like you described however as I plan to add more features to the right click context menus.
