### ISSUE TITLE
[Bug] MSQ & Job quest icons stuck on top left corner of the map

### ISSUE THREAD

**Issue by bnema** [MidoriKami/Mappy#41]
Hi, I encounter a weird bug with the icons of the MSQ and the job quest, they are stuck on the top left corner of the map ui.

I'm playing on a 4k screen with the UI scaling at 150% beside of that everything is vanilla-like. I also haven't touched at the config of Mappy so everything is default.

I'm adding a screenshot of the issue (The MSQ is supposed to be in this zone )
![bug_mappy](https://github.com/MidoriKami/Mappy/assets/5212137/9afa468b-6975-4c0a-a6ed-7dc78e299b26)

Thank you for your time and your awesome job !

**Comment by MidoriKami** [comment]
Duplicate of already posted and closed issues.
Update Mappy.

**Comment by bnema** [comment]
My bad I should have checked the closed issues, have a nice day
