### ISSUE TITLE
[Request] Missing icon and Fog of War

### ISSUE THREAD

**Issue by hsramm** [MidoriKami/Mappy#42]
![image](https://github.com/MidoriKami/Mappy/assets/36422849/f919391e-e3e8-48eb-83b0-e95f0fd8bd30)

That is missing from the map and the filters (I think this is a relatively new icon introduced in the game and I believe there are several more icons with that little arrow if the quest is inside a zoned instance...like Mor Dhona). Also is there any chance of getting a "Remove Fog" option so that alternate characters (or first-timers) can see what part of the map is uncovered for experience/achievement? Thanks a lot! It's looking really good btw.

**Comment by MidoriKami** [comment]
The missing icon has not been found yet in the gamedata, I've looked a few times and have been unsuccessful.

Fog of War will never be a feature of Mappy. I'm a strong believer that first-time players should not be using plugins until they are familiar with how the vanilla game works and have completed a significant portion of the story.
