### ISSUE TITLE
[Bug] Duty list centres map on marker that no longer exists

### ISSUE THREAD

**Issue by sersorrel** [MidoriKami/Mappy#44]
In the quest "The Admiral's Resolve" (post-ShB, patch 5.4), in the step "Speak with the leaders of Limsa Lominsa's pirate powers", I _think_ two MSQ markers appear on the map in the two locations you need to talk to someone – Mappy shows these correctly, but appears to always centre the map on the location of the first marker when you click on the quest step in the duty list, even if you've already spoken to that NPC (meaning that the marker no longer exists). With Mappy's integrations disabled, the vanilla map centres itself on the remaining MSQ marker.

Here's the location the vanilla map and Mappy open to when I click the quest, having spoken to one of the NPCs already:

![image](https://github.com/MidoriKami/Mappy/assets/9433472/a314619f-72bf-49a8-be22-e5a201d81dbc)

**Comment by MidoriKami** [comment]
There's nothing I can do about this issue.

Mappy will always zoom in on the first step of a quest that it finds for any given map id.
