### ISSUE TITLE
[Bug?] Mappy in PVP (Namely Frontline)

### ISSUE THREAD

**Issue by Rellawing** [MidoriKami/Mappy#47]
[Bug?] Mappy in PVP (Namely Frontline)

Why does Mappy not work in Frontline? It's wise to keep a map up in these activities. Mappy would be extremely useful in pvp. Not to reveal any more information than the normal map does. Just for the fact that it's big, transparent if set to be, and looks less clunky than the default map.

Also on a completely different subject... I wonder if you'd mind making a replacement for the minimap with more features sometime?

**Comment by MidoriKami** [comment]
No. And this is not up for debate.

I will never allow Mappy in PvP. Ever.
