### ISSUE TITLE
[Request] Add hotkey/toggle to use original map

### ISSUE THREAD

**Issue by robsims** [MidoriKami/Mappy#48]
There are a number of reasons I've wanted to use the original map rather than the plugin - using another plugin's feature that doesn't integrate well with it, taking screenshots of something on the map without showing that I'm using the addon, or preferring the original map when looking at something specific on it.

As far as I can tell the only way to trigger the original map to open is to open the XLPlugins menu and disable Mappy.  It would be useful to have either a settable hotkey or a toggle within the map menu or config to temporarily "disable" Mappy until it's toggled again.

**Comment by MidoriKami** [comment]
Disable integrations is already an option in the settings.
