### ISSUE TITLE
[Bug] Ghost quests appearing on the map

### ISSUE THREAD

**Issue by aradiel** [MidoriKami/Mappy#5]
So far I have witnessed them on two different maps:
![image](https://github.com/MidoriKami/Mappy/assets/22911153/6eb30c94-df48-4bf6-9a16-6925e64b5eea)
These appear to be the Hildibrand and MSQ quests, but both show up as level 0 and with no name. This character has completed both questlines already.
![image](https://github.com/MidoriKami/Mappy/assets/22911153/a99e65de-aa71-4e8a-a1ed-fd514475ef2f)
the same can be observed in Old Sharlayan. Based on position, these are likely from the variant dungeons.

**Comment by MidoriKami** [comment]
Does the Old Sharlyan quest have a tooltip string? Other than just `"Lv."?

**Comment by aradiel** [comment]
It's the same Lv. 0 as the others
