### ISSUE TITLE
[Request] Option to toggle map labels?

### ISSUE THREAD

**Issue by sunlightFrequency** [MidoriKami/Mappy#50]
Howdy, I'm not sure if I'm just missing an option or something, but I feel that the map is missing the subzone labels that the vanilla map has, which makes it easier for me to navigate to specific locations - for example, when filling out hunting logs or referencing mob locations for material drops and such. I know it's not to everyone's preference, but at least having the option to turn them on would save some folks a lot of headache, I think. I understand if it's not something worth the time or effort to implement, though.

The labels in question:
![image](https://github.com/MidoriKami/Mappy/assets/80407293/752d3296-12ab-4bd6-9dce-a8e8da6df8a8)

**Comment by MidoriKami** [comment]
Not planned, to render text with a shadow in ImGui each and every line of text has to be render 9+ times. It's not worth the performance hit.
