### ISSUE TITLE
Escape doesnt close when unfocused.

### ISSUE THREAD

**Issue by ZombieM0nk3y** [MidoriKami/Mappy#51]
I am not sure if this is an issue that CAN be fixed but I thought Id bring it up.. With the default map when you arent focused on the map hitting escape repeatedly will eventually close it as it goes through windows to close.. But with mappy it wont, you have to actually select it on the screen or close by hitting the map keybind. I had thought that  "Hide with game GUI" would fix this, but alas it doesnt.

I apologize if this is something that just cant be fixed, but I thought Id bring it up.

**Comment by MidoriKami** [comment]
That's just how it has to work.
