### ISSUE TITLE
[Bug] MSQ icon causes drops in FSP

### ISSUE THREAD

**Issue by swish29** [MidoriKami/Mappy#57]
At some point during play, opening Mappy results in considerable drop in FPS (let's say from 110 to 18).

Investigating what is the cause, I've narrowed it down to toggling Quests>Hide Accepted Quests. Specifically turning MSQ icon off seems to resolve it. I've encountered the issue on two separate play sessions, each time disabling MSQ would bring the FPS back to normal.

On last occurrence I've noticed that the MSQ icon was in place of blue + quest mark (see screenshot comparing Mappy and minimap). The MSQ icon should not even be in this place.
Besides that, disabling and enabling Mappy plugin resulted in performance going back to normal. Yet given couple of minutes, the Draw Time would creep up anyway. Suggesting there is ongoing increase in Draw Time that can be cleared with disabling/enabling Mappy.

Toggling MSQ icon off brings the Draw Time back to sub 0.4ms.

Please see screenshot below (disregard brightness all over the place due to HDR):
![image](https://github.com/MidoriKami/Mappy/assets/11081979/eaf1fb06-64f0-4818-b52b-7e7861294fa9)

Please let me know if there is any further information, traces or debugging I could provide.

Using Mappy 1.0.4.1, Dalamud 9.0.0.2.

**Comment by MidoriKami** [comment]
Thank you for your thorough investigation, I'll have to progress a little more in the story myself to test to see if my fix is working on not.

Look forward to an update in the next couple days.

**Comment by MidoriKami** [comment]
Fixed in beaace936bf8930554b848f0a3ae789b18870c9a
