### ISSUE TITLE
[Request] Auto-close When Entering Aesthetician

### ISSUE THREAD

**Issue by codeinclined** [MidoriKami/Mappy#58]
When going into the aesthetician, the map makes interacting with UI elements beneath it impossible. Pressing 'M' or trying to close it any other way seems not to work either. AFAIK, you have to just exit out of the aesthetician, close the map, and then re-enter. Not a big deal, but perhaps it'd be nice to have it auto-hide when you enter the aesthetician? If it's not easily possible to detect whether or not the player is in this mode, feel free to close this as it's just a minor inconvenience.

Thanks! I love this plugin!

**Comment by MidoriKami** [comment]
Indirectly addressed in 4cce9c4f968d318ffbeafac138082b3cad623750
