### ISSUE TITLE
[Bug] Quest availability does not update in real time

### ISSUE THREAD

**Issue by swish29** [MidoriKami/Mappy#59]
It seems that the quest availability does not update dynamically on job change (not sure about other conditions).
The example below shows a view of minimap, in-game view and Mappy of a job specific quest. Switching jobs updates the sate in-game and minimap, but Mappy still shows the same state.

Incorrect state:
![image](https://github.com/MidoriKami/Mappy/assets/11081979/e4c798b1-cffb-43f7-9bdb-4fb69b7a872c)
Expected state:
![image](https://github.com/MidoriKami/Mappy/assets/11081979/3b485b4d-5a55-45ab-845e-a9b466318fd3)

Toggling `Quests`  module does not update the state.
Disabling/Enabling the whole plugin or toggling `Hide Accepted Quests` updates the state of quest on Mappy to match in-game. Unfortunately no changes afterwards are are reflected.

**Comment by MidoriKami** [comment]
What version of Mappy.

**Comment by swish29** [comment]
1.0.5.0

**Comment by MidoriKami** [comment]
Excellent, v1.0.5.0 is a testing release that rebuilt the internal systems, bugs like this are exactly what I was hoping people would report.

**Comment by swish29** [comment]
You are fast ! :D Thanks 🥳
