### ISSUE TITLE
[Bug?] Map markers from Eureka Helper show on native map but not Mappy

### ISSUE THREAD

**Issue by foophoof** [MidoriKami/Mappy#60]
I'm not sure if this is an issue with Eureka Helper or Mappy, but that plugin has a tool to add possible Eureka Elemental spawn positions on the map, which adds moogle icons on the map. I see those icons on the native map and the mini-map, but when I use Mappy there's no icons at all. This seems to be the map marker code there: https://github.com/snorux/EurekaHelper/blob/59fab9e911149cff992f1976ff90f73a6efd0463/EurekaHelper/Utils.cs#L313-L339

I have all Mappy modules enabled, and I'm on v1.0.5.1, but I was on 1.0.4.5 earlier today and the issue was there too.

What the native map looks like:
![A cropped screenshot of the native map window](https://github.com/MidoriKami/Mappy/assets/22138688/6bf41870-251e-4926-9cf9-ef54d31a9cb5)

What Mappy looks like:
![A cropped screenshot of the Mappy window](https://github.com/MidoriKami/Mappy/assets/22138688/84dd270e-58bd-4e66-b8e5-bf2cdb9dd7b1)

**Comment by MidoriKami** [comment]
Not supported, Eureka Helper needs to use the provided Mappy IPC to add markers to Mappy.
