### ISSUE TITLE
[Request] Close Mappy for duration of a dialogue

### ISSUE THREAD

**Issue by swish29** [MidoriKami/Mappy#61]
Mappy already serves as great replacement for all cases where normal map is used via "Game Integrations". Window is opening in any cases where player would expect - via keybind, click on quest, etc.

For closing the window either the keybind ("Maps"), Escape Key or X button can be used. Even offering more options than normal map, like "Ignoring Escape Key" or closing automatically in certain situations via "Display options".

There are cases where Mappy does not follow normal map behavior. When talking to NPC the normal map closes while the dialogue prompt is on screen, then re-opens after dialogue is finished. Meanwhile Mappy stays open for the whole time. "Maps" keybind or Escape Key does not work on Mappy, but that is secondary (to me).
Looking through the issues there is https://github.com/MidoriKami/Mappy/issues/58, which suggests there might be other events that should temporarily be closing the normal map.

Besides aligning behavior with normal map, I'd personally use it for clean HUD for most gameplay. I hide normal in-game HUD parts using Fader plugin, but it does not have a way to do same for Dalamud plugin windows.

Filling this as feature request, since I don't recall Mappy behaving differently before. This might be intentional or a miss.

**Comment by MidoriKami** [comment]
Dalamud itself provides the options to hide plugin user interfaces during cutscenes (which quest dialogues trigger a cutscene).
You can view the condition flags yourself by using `/xldata condition`, anytime the cutscene flag is present the dalamud setting causes plugin windows to auto hide.

My intent was to simply let the users Dalamud setting dictate if it should hide or not, outside of the provided options.

![image](https://github.com/MidoriKami/Mappy/assets/9083275/1def080b-26ad-4727-b3d5-d5dd99251043)

**Comment by swish29** [comment]
Thanks for the pointer on `/xldata condition`, it is now more clear. 
Dalamud options for cutscene events work fine, as the options from the screenshot would suggest. For example when `ID: 35 Enum: OccupiedInCutSceneEvent` condition is met, Mappy does hide along with other Dalamud windows.

An example condition I've meant was for example `ID: 31 Enum: OccupiedInEvent` (talking to any NPC), `ID: 32 Enum: OccupiedInQuestEvent` (talking to quest NPC), `ID: 50 Enum: OccupiedSummoningBell` (opening Summoning Bell) and most likely bunch of others.

I'd imagine there is number of events that result in closing the normal map, that wouldn't be suitable for Dalamud to hide all plugin windows. Yet would seem to suit Mappy for hiding it own window.

PS. Please do let me know if there is a way to help out with this request.

**Comment by MidoriKami** [comment]
Mappy also provides the option to `Hide with game GUI` that pretty much satisfies all these conditions.

I'm not seeing any value in adding more specific flags than the options that are already available.

**Comment by swish29** [comment]
`Hide with game GUI` hides all GUI elements (along with Dalamud windows as per options above) on pressing a keybind.

I guess the idea behind hiding normal map on certain conditions was to reduce visual clutter during gameplay elements to give way to other menus or the game world. I do tend to align with that too, thus the request. For example opening Aethernet Shard closes normal map and places the Aethernet front and center:


https://github.com/MidoriKami/Mappy/assets/11081979/6ebd4087-f929-4564-b9a3-2e8d71d45383

**Comment by MidoriKami** [comment]
When you disable integrations you are literally disabling the code that would have hidden Mappy in that situation.

**Comment by MidoriKami** [comment]
I'm going to close this issue as not planned for now. 

I still have not seen any compelling reason to add more options than what I already offer at this time.

**Comment by swish29** [comment]
> When you disable integrations you are literally disabling the code that would have hidden Mappy in that situation.

Sure, but the behavior is still the same with Integrations enabled.

> I'm going to close this issue as not planned for now.
>
> I still have not seen any compelling reason to add more options than what I already offer at this time.

Thanks for consideration anyway.

**Comment by MidoriKami** [comment]
>> When you disable integrations you are literally disabling the code that would have hidden Mappy in that situation.

> Sure, but the behavior is still the same with Integrations enabled.

Then that's a bug and needs to be fixed.

**Comment by swish29** [comment]
I'm bit puzzled after the discussion above. Please see below:

https://github.com/MidoriKami/Mappy/assets/11081979/b53880a3-3466-41da-ac0f-78948120d6c2

My expectation with the selected options was that Mappy would close when Aethernet window opens up, and open again once it is closed. The same as normal map window it is replacing.
