### ISSUE TITLE
[Request] [IPC] Z-index, AddCircle, icon sizing

### ISSUE THREAD

**Issue by img02** [MidoriKami/Mappy#66]
Some features that would be nice (esp for IPC integration).

Z-Index - It seems that markers are drawn in order, with each added marker above the previous? It would be helpful to be able to set the Z-index of a marker to ensure it's always drawn below or above something else.

An example of how the player icon gets covered by icons I've added via the IPC functions.  

![image](https://github.com/MidoriKami/Mappy/assets/70348218/6432765c-02c5-433d-ac71-207fd98218e8)

AddCircle - It's sorta hard to find fitting icons to use. I've been able to draw some niceish shapes with the 'add line' function, that seems to use drawlist.AddLine, but it's a bit jank because it takes multple lines. (And you can't beat a nice round circle :D)

![image](https://github.com/MidoriKami/Mappy/assets/70348218/f3b2a2b0-afbd-440f-87a7-85d2027539d1)

Icon sizing - Seems icons just get drawn at their default size, some of which are quite larger. Being able to set a scale would allow for using a greater variety of icons in different ways. (though for me, I'd be happy just a bunch of circles)

![image](https://github.com/MidoriKami/Mappy/assets/70348218/333e23a5-b2fd-4565-b8dc-114f95f1905e)

Just some thoughts I had while playing around with the IPC.

**Comment by MidoriKami** [comment]
I'd be willing to merge a PR that added Circles and Icon Scale, but I am not really interested in Z-Index, as the consumer gets to control what order things are added to the list, and things are always drawn sequentially.
