### ISSUE TITLE
[Request] Command to open and close Mappy while integrations are off

### ISSUE THREAD

**Issue by mjexe** [MidoriKami/Mappy#68]
I've read through the closed requests and saw some similar requests but they didn't seem the same as this so I thought I would ask. It would be handy to be able to toggle Mappy while the original in-game map is open just because sometimes I use the in-game map for route planning and it would be nice to have a second map to look at other locations at the same time.

I know this is a niche feature and it's possible to show Mappy with integrations on and disable it to have them both visible but having a command to toggle Mappy would be really nice!

**Comment by mjexe** [comment]
I don't really understand why you won't add this as a feature.

**Comment by MidoriKami** [comment]
It's not up for debate. Every time I give reasons for my actions people want to argue, I am done arguing over every decision.
I have reasons for this decision, and those reasons wont change with a discussion/debate.
