### ISSUE TITLE
[Bug] Black Window inside Rising Stones

### ISSUE THREAD

**Issue by PayDQueso** [MidoriKami/Mappy#7]
Im Inside rising stones and mappy is showing a black window 
![image](https://github.com/MidoriKami/Mappy/assets/121763100/7d14c862-7d0d-4255-9ac1-e978e982d229)

**Comment by MidoriKami** [comment]
Set your in-game log to debug /xllog and then reproduce the issue and post your dalamud.log here

**Comment by MidoriKami** [comment]
![image](https://github.com/MidoriKami/Mappy/assets/9083275/70b852ed-6867-40fa-be32-6d490aba2a70)
Unable to reproduce.
