### ISSUE TITLE
Map does not display some quest info

### ISSUE THREAD

**Issue by SparkyMage** [MidoriKami/Mappy#70]
The map does not display icons for discussion spots on NPC escort quests, and many of the translated location names available on the vanilla map are not included in Mappy occasionally making finding fishing spots more difficult.

**Comment by MidoriKami** [comment]
This is known, I was unable to reverse engineer that game system to add those markers to Mappy. Code contributions are welcomed.

This is one of several reasons I insist that Mappy should not be used to replace the minimap.
