### ISSUE TITLE
[Bug]/[Request] Save the Queen critical engagements are not visible on map

### ISSUE THREAD

**Issue by CerulanLumina** [MidoriKami/Mappy#72]
As per title. 

Vanilla
![image](https://github.com/MidoriKami/Mappy/assets/1103450/680ed6e6-01cd-4f75-907c-be0b1f0b0d3d)

Mappy
![image](https://github.com/MidoriKami/Mappy/assets/1103450/b6342d6e-b6b9-4741-959f-d2d9a6b56cb8)

**Comment by MidoriKami** [comment]
Same response I gave in #70
