### ISSUE TITLE
[Request] Sort by "In-Game" sorting

### ISSUE THREAD

**Issue by AirDur** [MidoriKami/Mappy#74]
Basically, instead of having A-Z sort like this; ![image](https://github.com/MidoriKami/Mappy/assets/7089534/138dd1d7-5952-41a2-9837-eb3b66163479) 

I want to be able to have this kind of sort:
![image](https://github.com/MidoriKami/Mappy/assets/7089534/63f1457c-8b15-4992-8ba6-72b6312712d2)

It would be perfect.

(Should be possible by adding a parameter and use it [here to not order before creating HashSet](https://github.com/MidoriKami/Mappy/blob/master/Mappy/Views/General/MapRegionView.cs#L93C17-L93C37), I guess ?)

**Comment by MidoriKami** [comment]
I tried to do that before, didn't work correctly. Alphabetical was next best option.

**Comment by MidoriKami** [comment]
If you can get it to work correctly without hardcoding the order, then I would likely accept a PR.
