### ISSUE TITLE
[Request] Vnavmesh integration

### ISSUE THREAD

**Issue by Flavescent** [MidoriKami/Mappy#77]
The vnavmesh plugin (https://github.com/awgil/ffxiv_navmesh) allows the user to automatically move the player character in a terrain-aware manner to a specific location, using the command "/vnavmesh moveto <X> <Y> <Z>", or "/vnavmesh flyto <X> <Y> <Z>" for flight.

I propose to add a "Move here" command to the Mappy context menu if vnavmesh is installed. This context menu entry would execute the "/vnavmesh moveto" command with the coordinates of the cursor location, or "/vnavmesh flyto" if flight is available in the current map.

**Comment by MidoriKami** [comment]
Absolutely not. I will not allow or support any form of automation or botting. This goes directly against dalamuds plugin rules.
