### ISSUE TITLE
[bug] 'draw aetherytes on top' option not actually drawing aetherytes on top of anything

### ISSUE THREAD

**Issue by neongrey** [MidoriKami/Mappy#79]
you can click through even though you can't see much of it here and it'll still work but the option is not functional and the keybind to move the aetherytes to the top from the og map doesn't work (that is not a request; i assume it's like that for a reason, just clarifying that there appears to be no way to put the aetheryte on top).

![3b4f19a29a 1](https://github.com/MidoriKami/Mappy/assets/17973965/8298fa63-2b47-45db-a6ab-eeecc160cc3f)

**Comment by MidoriKami** [comment]
Superseded by Mappy v2.0.0.0
