### ISSUE TITLE
Omnicron Beast Tribe Quests - Showing All Locations

### ISSUE THREAD

**Issue by FromTheGrayve** [MidoriKami/Mappy#8]
It appears the Omnicron Daily Quests are showing all options for where the quest objective is located. 

I was on Miner, level 90

A Brewing Repulation - Map is showing all possible spawn locationsm while the minimap points toward the correct loction (Which is South East, by the Omnicron Aetherite. The north and  south west markers are wrong for this day)

Well Below Standard -  
A) It seems to be showing all gather locations, not filtering by class. I believe it is North Orange Circle is for fishing, Middle for Botanist, South for Mining
B) Even though I have harvested the materials, the gather locations remain highlighted
![Omnicron](https://github.com/MidoriKami/Mappy/assets/56549939/0bf4dca2-cf02-4bc7-b4f6-28123930664e)

**Comment by MidoriKami** [comment]
> It appears the Omnicron Daily Quests are showing all options for where the quest objective is located.

This is intentional, currently there is no way to filter those. This applies to all Tribal Quests.

Markers will remain active until the completion of the quest.
