### ISSUE TITLE
[bug] cannot minimize config window

### ISSUE THREAD

**Issue by neongrey** [MidoriKami/Mappy#80]
if you attempt to minimize the config window, the window just flashes shut for a moment and immediately reopens. i checked it with the map unlocked and locked; thought there might be a relation but guess not

![ezgif-1-04a04f917b 1](https://github.com/MidoriKami/Mappy/assets/17973965/acbaf3b8-d338-4d8e-9387-a7381519fba3)

**Comment by MidoriKami** [comment]
Superseded by Mappy v2.0.0.0
