### ISSUE TITLE
[Bug] The icon for yet to unlock gemstone traders is way too big compared to other map icons

### ISSUE THREAD

**Issue by GayPotatoEmma** [MidoriKami/Mappy#85]
The icon that indicates a Gemstone trader that you have yet to unlock appears oversized in both the map window aswell as the icon settings. This seems to happen regardless of icon scale settings.

- Map view
![image](https://github.com/MidoriKami/Mappy/assets/153868115/3c282634-3fa2-49dd-94f8-7836f704d3e4)

- Icon settings
![image](https://github.com/MidoriKami/Mappy/assets/153868115/fd7d912a-5491-44ce-bcf2-fd8fa6de0e73)

**Comment by MidoriKami** [comment]
Mistaken reference to 106, issue is unrelated.
