### ISSUE TITLE
[Bug] Some quests open to the wrong map when clicked

### ISSUE THREAD

**Issue by GayPotatoEmma** [MidoriKami/Mappy#86]
Some quests appear to open to the wrong map when clicking the objectives from the vanilla quest list. Pressing the quest from Mappy's own quest menu will open it to the correct location. Pressing the quest list with the vanilla map will also open to the correct location confirming that the quest data should atleast be correct.

Example:
- Lv100 | The Hunt Goes On
  - Step: Report back to Bol Ogaw in Tuliyollal
    - When pressed in the quest list
      ![image](https://github.com/MidoriKami/Mappy/assets/153868115/f7c85779-1973-4f22-b38a-21f8019061ad)
    - When pressed from Mappy quest menu (correct)
      ![image](https://github.com/MidoriKami/Mappy/assets/153868115/4143fa04-675a-45b9-8bc8-2366c93b328b)

If any other quests appear to be affected I will add them here:
- Lv100 | Trial By Spire

**Comment by MidoriKami** [comment]
Can you provide a short recording?

**Comment by GayPotatoEmma** [comment]
I'll have to find another affected quest, I foolishly turned in the quest so it may take a little bit before I can post the recording

**Comment by GayPotatoEmma** [comment]
https://streamable.com/aeq2g0 Here you go, recording this also made me find another bug with the Quest Window so I'll be filing a seperate issue for that

**Comment by MidoriKami** [comment]
Potentially fixed, but probably not.

**Comment by TheLostSoul** [comment]
If it helps to have more test cases, I noticed this happens on "The Crate Beyond" (Picto 85 quest) final step also (Deliver the saltworn crate to the aidless trader.)
As well as clicking flag links to other zones in chat sometimes when I already have the map open. First click will only open the current map, but clicking it a second time will open the correct location (not sure if it's related).

**Comment by diabolicbutterfly** [comment]
I've noticed this happens on most of the new quests only...

**Comment by boogieman1402** [comment]
I'm running into this as well with various quests. Using https://ffxiv.consolegameswiki.com/wiki/Blood_for_Stone as a step by step example:
- I've done Stone Vigil, so the quest is at the final step (Report to Drillemont)
- Clicking it from the Mappy Quest list window makes mappy jump straight to courthas and focus on the correct location
- Clicking it from the vanilla quest list, it opens the map for stone vigil but with the quest marker way outside the dungeon. The location for the quest marker doesn't match the actual location of the quest npc on the correct map either.

I've tried toggling the option 'Remember Last map', but this doesn't appear to make a difference.

Two screenshots, hope they help:
https://i.imgur.com/CLoQ98h.png
https://i.imgur.com/fX16ElM.png

**Comment by StellarJay77** [comment]
Having the same issue. This seems to happen for quest links for places in Tuliyolial mainly. The last quest of the Healer role quest "An Antidote for Anarchy" has the quest state ">Speak to Nyipine in Tuliyolial" and clicking on both that text in the vanilla quest list and the map button in the quest itself seem to bring up the World Map for me with a Green check mark blue+ marker in the middle. See screenshots.

![image](https://github.com/user-attachments/assets/3caba08b-1519-4eb5-8c9f-780e19963b41)
![image](https://github.com/user-attachments/assets/fc5ef3e8-13f9-4e17-b3bb-8112eb16c03b)

**Comment by DormantLime** [comment]
> Having the same issue. This seems to happen for quest links for places in Tuliyolial mainly. The last quest of the Healer role quest "An Antidote for Anarchy" has the quest state ">Speak to Nyipine in Tuliyolial" and clicking on both that text in the vanilla quest list and the map button in the quest itself seem to bring up the World Map for me with a Green check mark blue+ marker in the middle. See screenshots.
> 
> ![image](https://private-user-images.githubusercontent.com/61530662/351713000-3caba08b-1519-4eb5-8c9f-780e19963b41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzY2MjYsIm5iZiI6MTcyMTgzNjMyNiwicGF0aCI6Ii82MTUzMDY2Mi8zNTE3MTMwMDAtM2NhYmEwOGItMTUxOS00ZWI1LThjOWYtNzgwZTE5OTYzYjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE1NTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwODRmM2E3YWVmYzIyZTMwMjZiMjRjNWMyMWJiZDAzNTc4MzVmMzZmYjNmNTIyYTQ3MzRhNmUxYzI4NWEyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RcPz3XqTDEBFKAp8Ggwu4Wn0GFMiAYGHhGrIk_PKIE0) ![image](https://private-user-images.githubusercontent.com/61530662/351713203-fc5ef3e8-13f9-4e17-b3bb-8112eb16c03b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzY2MjYsIm5iZiI6MTcyMTgzNjMyNiwicGF0aCI6Ii82MTUzMDY2Mi8zNTE3MTMyMDMtZmM1ZWYzZTgtMTNmOS00ZTE3LWIzYmItODExMmViMTZjMDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE1NTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNTRiYmNjMDIwYTNlYjdkNGNkMzIzODIyOTRkZTJiNDAxZDNiODQ0YzIyYTQ2MWQyMGNhMDA5YThlMzNhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ABdVJQKFTnF7eVNqB4bsfBgTAbcmiTzTT7EBna3Qjk)

I am experiencing this exact issue, but with my Summoner quests taking me to Gridania. It shows me the world map with a quest marker where Gridania is, but doesn't take me to the Gridania map.

**Comment by MidoriKami** [comment]
Topic moved to #150
