### ISSUE TITLE
[Bug] Dropdown menus in the toolbar don't work properly if "Always show" is disabled

### ISSUE THREAD

**Issue by GayPotatoEmma** [MidoriKami/Mappy#88]
Attempting to use any of the dropdown options in Mappy's toolbar doesn't seem to work properly if you have the toolbar set to only show when you mouse over it. Any dropdown option that goes below the toolbar area will cause the toolbar to hide and thus also close the dropdown menu.

https://streamable.com/4w9ewa

**Comment by MidoriKami** [comment]
I just came across this myself recently, I knew that the toolbar stops existing for a frame when moving your mouse out from under it, but I didn't think it'd have a consequence like this.

Thanks
