### ISSUE TITLE
[Request] Integration with (or implementation of) Mini-Mappingway

### ISSUE THREAD

**Issue by mishugashu** [MidoriKami/Mappy#9]
https://github.com/jaycewhite/MiniMappingway

It'd be great if this feature could be implemented, or integrate with the plugin. I could replace my mini-map with this plugin! :D

**Comment by MidoriKami** [comment]
Mappy is explicitly not intended to be used as a minimap.

It will never have all of the functionality that the minimap provides. Do not use Mappy as a Minimap.
