### ISSUE TITLE
[Bug] Can't see party members on map if they're far away

### ISSUE THREAD

**Issue by GayPotatoEmma** [MidoriKami/Mappy#91]
Unlike on the vanilla map, Mappy doesn't display a marker for party members that are outside of the rendering range.

- Vanilla
![image](https://github.com/MidoriKami/Mappy/assets/153868115/11fa68b2-e7b3-4514-a352-988966ae135b)

- Mappy
![image](https://github.com/MidoriKami/Mappy/assets/153868115/86f6e1a8-7ae6-463e-927d-9638140ca7b5)

*Party member did not move inbetween these screenshots ofcourse*

**Comment by MidoriKami** [comment]
Hmm it's not showing party members it's showing gameobjects and I limit the range so that things on other layers don't show. Not sure if I'm going to address this one.

**Comment by RaidenvBlack** [comment]
If it should replace the ingame Map it should also show the party members position that is in my opinion an essential feature

**Comment by zbee** [comment]
It really holds Mappy back in overworld content, e.g. fates and hunt trains. This should be an exception to the range limit for sure especially considering this is more limiting than Vanilla.
