### ISSUE TITLE
X and Y coordinates

### ISSUE THREAD

**Issue by Solace9** [MidoriKami/Mappy#95]
Would be very useful! e.g finding certain Npc's when guided by X and Y coords

**Comment by MidoriKami** [comment]
Please elaborate, x and y where? How? What format? World coordinates? Map coordinates?

**Comment by Solace9** [comment]
Much like how the regular map has them, where they update the x and y coords based on the position of your mouse on the map
for the regular map they're in the top right corner,

Here's a gif showcasing what i mean
![1NWCHfN](https://github.com/MidoriKami/Mappy/assets/167470284/faa5e8fc-cc94-4897-9510-c21c7673f581)

**Comment by MidoriKami** [comment]
Proposed implementation that I liked from Discord

![image](https://github.com/user-attachments/assets/4d292410-7d5d-4aff-86b8-544d44eb09b5)

**Comment by Solace9** [comment]
Yeah, i think that'd be great!
