### ISSUE TITLE
Penumbra IPC borked (obviously)

### ISSUE THREAD

**Issue by Shiichibukai** [MidoriKami/Mappy#97]
![grafik](https://github.com/MidoriKami/Mappy/assets/96307333/182957cf-f5bb-482a-91a7-00af64abfd05)
The map shows empty due to not being able to pull the proper texture I assume because of penumbra still being in the very early testing phase - I would guess its prob gonna be on your radar but figured i'd make an issue regardless (chromatized map user here) 

They work normally on normal map.

**Comment by MidoriKami** [comment]
There is no penumbra IPC, I load my textures through dalamuds texture provider. This is a penumbra issue.

**Comment by MidoriKami** [comment]
Clarification, this means penumbras texture substitution provider which tells dalamud to use different textures, isn't working correctly.
