### ISSUE TITLE
[Bug] Quest markers persist upon changing maps

### ISSUE THREAD

**Issue by GayPotatoEmma** [MidoriKami/Mappy#98]
Quest markers appear to persist on the map when you switch maps. This happens regardless of whether remember last map is turned on. 

https://streamable.com/gl9gb1

May also happen with other markers on occassion, but have not found a reliable way to reproduce with those:
- Housing markers (as mentioned by someone in the Mappy thread)

**Comment by MaddoxMaxx** [comment]
I noticed this starts to happen more when click the blue quest text from the quest listing in the HUD. For me It takes me to the quest marker but usually with an incorrect map area.
