### ISSUE TITLE
Gemstone trader icon is huge despite being 1.0 scale

### ISSUE THREAD

**Issue by nicuity** [MidoriKami/Mappy#99]
![gemstone trader](https://github.com/MidoriKami/Mappy/assets/175070634/07678eed-6cd1-4875-80ba-eda3ba837705)

**Comment by nicuity** [comment]
Ok ignore this. Didn't expect the plugin to enlarge it to remind you to talk to the npc. My bad lol.

**Comment by MidoriKami** [comment]
Duplicate #85
